### PR TITLE
Updated for issue 20 and 21

### PR DESCRIPTION
**Pull request by agupt013**
I updated the README.md file based on issue #20 and #21 and added the following paper. It would be great if you could check and merge this branch for updated papers.

Adversarial Knowledge Transfer from Unlabeled Data. Gupta et al. ACM-MM 2020 [code](https://github.com/agupt013/akt)

### CODE REVIEW

**Comment by fawazsammani** [comment]
@agupt013 can you add these cvpr 2022 papers as well to your pull request? Thanks

DearKD: Data-Efficient Early Knowledge Distillation for Vision Transformers: https://arxiv.org/pdf/2204.12997.pdf
Knowledge Distillation with the Reused Teacher Classifier: https://arxiv.org/pdf/2203.14001.pdf
Self-Distillation from the Last Mini-Batch for Consistency Regularization: https://arxiv.org/pdf/2203.16172.pdf
Decoupled Knowledge Distillation: https://arxiv.org/pdf/2203.08679.pdf

**Comment by agupt013** [comment]
Added this to my new commit along with issue #23 . Will raise a merge request.

**Comment by agupt013** [comment]
@FLHonker Can you please approve the merge request?

**Comment by fawazsammani** [comment]
@agupt013 can you add the papers I mentioned in Issue #21 to your PR? Thanks

**Pull request merged**
